# Generated by Django 6.1.1 on 2026-09-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='quantite_preoduits',
            new_name='quantite_produits',
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_suivante',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='high_level.operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='quantite_produits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='high_level.quantiteproduit'),
        ),
    ]
