# Generated by Django 6.1.1 on 2026-09-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("high_level", "0002_rename_quantite_preoduits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="operation_suivante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.operation",
            ),
        ),
    ]
